### ISSUE TITLE
Results grid columns sized to column name and not column data on query first run (RM #7458)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5132]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7458***
*Originally created by **David Chalmers** at 2022-06-08 01:38:58 UTC.*

As per the subject, the results grid columns are sized according to the column name width and not to the column data width the first time a query is run within a query tool tab. Any subsequent run of the query/ies will correctly size the columns.
This appears to be new since v6.8.

**Comment by pravesh-sharma** [comment]
Fixed in latest snapshot build.

**Comment by stevstrong** [comment]
This change lowers the user experience.
Before, I could set the column width to a very small size. Now, the minimum size it is set to an arbitrary value, not the column data and not the column name, independent on the preferences setting.
Before, I could set the column size and this remained at this value for any subsequent query. Now, it is set again to the arbitrary value at any further query.
Please indicate how could I bring back the previous column sizing features?

**Comment by adityatoshniwal** [comment]
@stevstrong Did you try on pgAdmin v6.15 ?

**Comment by stevstrong** [comment]
Yes.
![image](https://user-images.githubusercontent.com/9655070/199457890-d2546b07-b00d-4497-ad61-2cc83a74aa4c.png)

**Comment by stevstrong** [comment]
I have found the last version where the result columns keep their width after refresh is v.6.9. The newer ones reset the width on refresh.
Unfortunately I cannot find the earlier 6.x versions to download, but I still have locally the v6.6 which allows me to set a minimal column width, down to only 1 character visible.
Until this is issue is not resolved, I have to stick to this version.

**Comment by yogeshmahajan-1903** [comment]
Created a separate issue #5499.
