### ISSUE TITLE
pgAdmin 'Browser' window disappears frequently (RM #7670)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5306]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7670***
*Originally created by **Hiren Shah** at 2022-09-02 15:07:29 UTC.*

Hello,

I am seeing issue with 'Browser' window disappearing frequently, and have to do 'Reset Layout' to bring it back.

Version
6.13
Application Mode
Desktop
Current User
pgadmin4@pgadmin.org
NW.js Version
0.62.2
Browser
Chromium 99.0.4844.84
Operating System
Windows-10-10.0.19042-SP0

Downloaded from pgAdmin website.

Thanks,
Hiren Shah

**Comment by cklein05** [comment]
Hi there,

I'm experiencing the same issues (likely) for a longer time now. Either the content of the tree on the left side of the content of a certain tab panel on the right side (e. g. SQL console) suddenly disappear. In my cases, clicking _Restore Layout_ does not bring back the disappeared content.

Also, it's quite hard or impossible to reproduce this behavior, as there is no systematic visible on when that happens. Currently, I was working in a SQL window and clicked menu *Edit* -> *Replace* which triggered the SQL panel to disappear. More often the tree on the left side disappears. That may be triggered by just clicking on a tree item or choosing one the the context menu items.

In all cases, I had to close an restart the the Windows Desktop version of pgAdmin 4, loosing most of my not yet committed changes (e. g. DDL or changes in complex PL/pgSQL or Python functions).

Currently I'm using version 6.13, however this type of bugs occurs for several months already so, older versions seem to be affected as well.

As already said, that is *not* reproducible and does not happen very often. However, when working on a professional project with a tight schedule, even two or three such events a day is far too much and doesn't help creating happy users (actually, this draws this tool quite non-professional and produces quite angry users...).

Unfortunately, I have not idea how to support you in finding out more about that issue. I guess, that someone just set the visibility of the panel to 'hidden'. However, as we don't have some Chrome Dev Tools around in pgAdmin 4, I have no real insights.

Cheers
Carsten

**Comment by cklein05** [comment]
Opps. just happened again. I was typing in the _Search_ field of the Query-Tool (using regular expressions). This worked fine while typing some characters and the whole panel disappeared after typing another character. As far as I remember, the last typed character was an opening bracket, making the regular expression *invalid* (it gets valid only after entering the closing bracket). Maybe the (internal) RegExp error 'invalid pattern' may be a trigger for that issue. However, sometimes entering regular expressions (valid or invalid) works without any problems.

The attached image shows the situation afterwards (it's in German language).

![image](https://user-images.githubusercontent.com/8255621/190592355-f89a54d3-68b4-4de7-ac70-305804264a64.png)

**Comment by cklein05** [comment]
Additional note: I cannot close the tab whose content has disappeared. I can open new tabs and close them. Seems like I can use the application as usual, except I just can't access the vanished tab anymore (of course) nor can I close it.

**Comment by nikhil-mohite** [comment]
Hi @cklein05,

The query tool crash is fixed with the latest release v6.14 (https://github.com/pgadmin-org/pgadmin4/commit/a2a18d4b4af5dbd8efb46260ab0863faa0f24b2f).

**Comment by RP-natanaraujo** [comment]
I dont know how to reproduce that, but happens to me for the past months.
My browser tree turn into a white pane when I click some resource of tree (sometimes).
I think that happens since react migration of tree, but I'm not so sure.

To solve my problem I just refresh the page and to not lose my query tool, already config to open in separate browser tab so I can refresh without losing my code.
![image](https://user-images.githubusercontent.com/104854054/196431652-d04e0066-61cb-4096-b0a3-13a8b4f8c1ce.png)

**Comment by RP-natanaraujo** [comment]
If help, happened to me again, but this time was a little different.
My browser tree shrink, but don't turn all blank.

Maybe is something related to responsive design breaking div height.
![Screen Shot 2022-10-18 at 15 29 14](https://user-images.githubusercontent.com/104854054/196515378-7565d879-e8c1-4a0f-aa4d-94216da75fa5.png)

**Comment by svinsightdata** [comment]
This is indeed very difficult to produce a description for how to reproduce the issue. It is not clear to us was action triggers this behaviour. All of our users report this behaviour with people using both Windows 10 and Windows 11. PG Admin version 6.14
Like RP-natanaraujo reports, in some cases the entire browser disappears and in some cases the browser element height is not correct, and reseizing the window has no effect.

**Comment by RP-natanaraujo** [comment]
@adityatoshniwal I'm with 6.15 now and still happens.
![Screen Shot 2022-10-25 at 09 36 48](https://user-images.githubusercontent.com/104854054/197775049-2bd47c07-aecc-42e5-9efe-6430c2590b4c.png)

**Comment by adityatoshniwal** [comment]
@RP-natanaraujo The height issue was fixed. The team is looking into this one.

**Comment by svinsightdata** [comment]
@adityatoshniwal Sorry for the late response. We are currently on version 6.16, and we are experiencing the issue. With some actions the browser disappears. Horizontally resizing the browser then triggers it to redraw and the brower then appears again. 
The height issue is fixed. We are not experiencing that anymore.

**Comment by jcampbellGoPuff** [comment]
I keep hitting this issue in 6.19 and it's frustrating.  I wonder if it is related to VPN use.  Please review when possible.  In the meantime, I'll try the horizontal resize and see if it helps.

**Comment by nl-savills-insightdata** [comment]
In my experience the browser tree flickering + disappearing on horizontal resize is still present.
Windows 11 H2, pgadmin v6.21
also see #5559

**Comment by adityatoshniwal** [comment]
Steps to reproduce - https://github.com/pgadmin-org/pgadmin4/issues/6266#issuecomment-1587325962

**Comment by EFrankel-ITEP** [comment]
Issue appears to be fixed.
https://github.com/pgadmin-org/pgadmin4/issues/6266#issuecomment-1603042561

**Comment by nikhil-mohite** [comment]
Resolved, Verified on latest snapshot build: https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-06-23/
OS: macOS (Ventura 13.3)
Mode: Desktop
(Tested using steps provided [#6266 (comment)](https://github.com/pgadmin-org/pgadmin4/issues/6266#issuecomment-1603042561))
