### ISSUE TITLE
UI Resets on each load of the Application

### ISSUE THREAD

**Issue by PaulFarry** [pgadmin-org/pgadmin4#6399]
I'm running pgAdmin 4 (7.3) on Windows.

When I the Application it I get a very small version of the user interface.

![image](https://github.com/pgadmin-org/pgadmin4/assets/81415/e51f855d-0046-4d61-872a-ba996349dac2)

I then go to file -> Reset Layout
and Find the Yes button and Confirm.

```
Reload Site? 
Changes that you made may not be saved.
[Reload] [Cancel]
```

![image](https://github.com/pgadmin-org/pgadmin4/assets/81415/dfdb535b-6a15-4984-bc71-cb63b898f3c9)

I then get an operation UI for the current running instance.

![image](https://github.com/pgadmin-org/pgadmin4/assets/81415/7d40478d-b5c4-4a4f-810a-a46c5dfb63a7)

When I then exit the application this process repeats.

The same behavior was exhibited for many versions of 6.x

**Comment by khushboovashi** [comment]
Hi @PaulFarry, 

Can you please provide your screen resolution?

**Comment by pauliusg** [comment]
The same for me, I just have too big elements (looks like layout from my laptop screen. While most of the time I am using external monitor. I always have to choose "Reset Layout" when I start PG admin, as after reset proper layout is not persisted. I can click "Reset Layout", exit and start again and the the same issue :-( 
My version: 6.21.

**Comment by amauri-apexlogikdata** [comment]
Same here
pgAdmin 7.4
OS Windows 10
![pgAdmin2](https://github.com/pgadmin-org/pgadmin4/assets/78664861/7dc3a2ff-81a2-4f74-9849-644878f7a543)

**Comment by amauri-apexlogikdata** [comment]
How I fixed that problem:
I did full uninstall and install pgAdmin again.

**Comment by ottojens** [comment]
Sadly, this did not change anything for me, despite that I manually delete all the remains after uninstalling.

**Comment by PaulFarry** [comment]
I’ve just tested it too. Latest version and it’s needing to be reset each
time I open pgadmin.

**Comment by ottojens** [comment]
@khushboovashi it's still the same odd behaviour with v7.6 (at least for me, running the binary under windows)

**Comment by PaulFarry** [comment]
@khushboovashi @akshay-joshi  I have just downloaded 7.6 version and done the same test. 

Open, Size microscopic.. Reset Layout. Works for Current Session.
Close PGAdmin, reopen, Size Microscopic again.

Is it possible it's some setting that you could give a guide for or check for that is broken and then pop a dialog.

"Your settings appear to be `broken`. Would you like to reset (x) setting and re-open." [As long as it's a real fix].

Then at least the neverending loop of reset Layout can be stopped?

Could you supply me with details about how I can get you a copy of the settings file(s) [locations etc] that you need so that you can reproduce?

**Comment by PaulFarry** [comment]
@akshay-joshi  How are we looking on this issue? It's been ongoing for a long time now, and I'd just like to know how I can help? Is there something that you need from me or something that I can do that would make it easier for you/your team to be able to repro/find the issue?

**Comment by adityatoshniwal** [comment]
It looks the issue occurs when using multiple monitors. Can you confirm @PaulFarry?

**Comment by PaulFarry** [comment]
Yes, confirmed. I have 2 monitors of the same size and resolution.
2560x1440.

**Comment by adityatoshniwal** [comment]
HI @PaulFarry,
Do pgAdmin work fine if you disconnect one of the monitors?

**Comment by PaulFarry** [comment]
@adityatoshniwal I have disconnected the 2nd monitor and still I have the micro display. I reset layout (display normal). I close pgadmin, reopen and micro display again.

I also tested forcing the display resolution to 1920x1080 and reopening. Still Micro display, reset layout (normal), then close and reopen, back to micro display. 

I also restarted the machine with the resolution changed just to make sure that there wasn't a service that only detected on system startup. No improvement

**Comment by freightverifianbrian** [comment]
I have been having this same issue for a little while as well.

APP_VERSION = "7.8"
I use a monitor in addition to my laptop via a Surface Dock.
Windows 11
Primary Monitor resolution : 3840 x 2160 with 150% Scale 
Laptop monitor resolution : 3000 x 2000 with 175% scale
I have been using the "Reset Layout" function every time I open the application, in the hopes that this would be resolved soon... however I have now upgraded to PgAdmin4 v8 and the "Reset Layout" function does not even work, so I have now had to go back to PgAdmin4 v7

**Comment by adityatoshniwal** [comment]
Hi @freightverifianbrian, @PaulFarry,
Please replace the attached file (pgadmin.js) in your pgAdmin4 installation at `C:\Program Files\pgAdmin 4\v6\runtime\src\js`.
After replacing, start pgAdmin and share the logs from File->Runtime->View logs.
[pgadmin.js.zip](https://github.com/pgadmin-org/pgadmin4/files/13576574/pgadmin.js.zip)

**Comment by PaulFarry** [comment]
@adityatoshniwal Unfortunately I can no longer reproduce this issue, I endedup uninstalling PG admin, and then searching for every trace of configuration and deleting it from my machine. I then re-installed PGAdmin and whilst it was painful setting up the servers again, the issue is gone.

**Comment by pauliusg** [comment]
@adityatoshniwal Update, installed v8.0 but I have have the same issue. Wrapped failing part with try catch:
 ```javascript
try {
    pgadminWindow.window.hookConsole((method, args) => {
        misc.writeServerLog(
            `--------------[UI ${method}]---------------${EOL}${misc.parseConsoleArgs(method, args)}${EOL}------------[UI End]----------------`);
    });
} catch (e) {
    misc.writeServerLog('Error on hookConsole' + JSON.stringify(e.message, null, 4));
}
```

Logs show: Error on hookConsole"pgadminWindow.window.hookConsole is not a function".

**Comment by adityatoshniwal** [comment]
> @adityatoshniwal Update, installed v8.0 but issue is the same. Wrapped failing part with try catch:
> 
> ```js
> try {
>    pgadminWindow.window.hookConsole((method, args) => {
>        misc.writeServerLog(
>            `--------------[UI ${method}]---------------${EOL}${misc.parseConsoleArgs(method, args)}${EOL}------------[UI End]----------------`);
>    });
> } catch (e) {
>    misc.writeServerLog('Error on hookConsole' + JSON.stringify(e.message, null, 4));
> }
> ```
> 
> Logs show: Error on hookConsole"pgadminWindow.window.hookConsole is not a function". I run it on Windows.

I will update the file and send again.

**Comment by pauliusg** [comment]
@adityatoshniwal, found that hookConsole function is in file  https://github.com/pgadmin-org/pgadmin4/blob/master/web/pgadmin/browser/templates/browser/index.html

File on my local installation from  differs:
![image](https://github.com/pgadmin-org/pgadmin4/assets/1721818/c81ce39e-246b-4785-8b65-490df2285ca5)

I will try to uninstall PgAdmin and install again, but I need to find if Servers will remain in such case...

**Comment by pauliusg** [comment]
@adityatoshniwal, after reinstall it works. Logs:
```
Screens:[
    {
        "bounds": {
            "height": 1440,
            "width": 2560,
            "x": 2048,
            "y": -345
        },
        "id": -1515868891,
        "isBuiltIn": false,
        "rotation": 0,
        "scaleFactor": 1,
        "touchSupport": 0,
        "work_area": {
            "height": 1400,
            "width": 2560,
            "x": 2048,
            "y": -345
        }
    },
    {
        "bounds": {
            "height": 1152,
            "width": 2048,
            "x": 0,
            "y": 0
        },
        "id": -1453398824,
        "isBuiltIn": false,
        "rotation": 0,
        "scaleFactor": 1.25,
        "touchSupport": 0,
        "work_area": {
            "height": 1112,
            "width": 2048,
            "x": 0,
            "y": 0
        }
    },
    {
        "bounds": {
            "height": 864,
            "width": 1536,
            "x": 4608,
            "y": -273
        },
        "id": -1766234852,
        "isBuiltIn": true,
        "rotation": 0,
        "scaleFactor": 1.25,
        "touchSupport": 0,
        "work_area": {
            "height": 824,
            "width": 1536,
            "x": 4608,
            "y": -273
        }
    }
]
pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "C:\Program Files\pgAdmin 4\python\python.exe"
Runtime Config File: "C:\Users\paulius.grabauskas\AppData\Roaming\pgadmin\runtime_config.json"
pgAdmin Config File: "C:\Program Files\pgAdmin 4\web\config.py"
Webapp Path: "C:\Program Files\pgAdmin 4\web\pgAdmin4.py"
pgAdmin Command: "C:\Program Files\pgAdmin 4\python\python.exe -s C:\Program Files\pgAdmin 4\web\pgAdmin4.py"
Environment: 
	- [ I have removed this part as it has sensitive info]
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.057 Sec
2023-12-07 09:28:10,497: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.

 * Serving Flask app 'pgadmin'
 * Debug mode: off

------------------------------------------
Total time taken to ping pgAdmin4 server: 9.272 Sec
------------------------------------------
Total launch time of pgAdmin4: 10.247 Sec
------------------------------------------
Application Server URL: http://127.0.0.1:64446/?key=i_have_removed_key
Zoom level:0
```

**Comment by pauliusg** [comment]
In v8 reset layout does not work, but I can control Zoom with Ctrl + +/- keys (just use those from main keyboard, not from numpad). Zoom is persisted on exit.

**Comment by adityatoshniwal** [comment]
@pauliusg Reset layout used to reload the page, and all the open tabs were lost. So it was improved to not reload the page.
We might need to add a `Reload Page` option though.
As per the logs, the zoom level is 0 which is correct. It is more related to NW.js container which is based on chromium. Trying to figure out a workaround.

**Comment by pauliusg** [comment]
@adityatoshniwal, I am happy how v8 works, even Reset Layout now works is different. 
The main thing is that **Zoom is persisted**, so don't need to do anything when I start PgAdmin next time. 
So, from my perspective, I don't have issues anymore.
