### ISSUE TITLE
Options key not registering in PSQL CLI tool

### ISSUE THREAD

**Issue by barunps3** [pgadmin-org/pgadmin4#6968]
I am using Macbook Pro (intel) with German Keyboard. 
To type blackslash I need to press Shift + Options + 7. 
However, backslash is not inputed in PSQL CLI Tool. 
And this also the case when have to type [ with Option + 5.
So it seems the Options key input is not registered by PSQL CLI tool. 

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - Version: 14.0
 - Mode: Desktop
 - Keyboard: German (not German - Standard)

**Comment by akshay-joshi** [comment]
Hi

On Wed, Nov 15, 2023 at 12:35 AM barunps3 ***@***.***> wrote:

> I am using Macbook Pro (intel) with German Keyboard.
> To type blackslash I need to press Shift + Options + 7.
> However, backslash is not inputed in PSQL CLI Tool.
> And this also the case when have to type [ with Option + 5.
> So it seems the Options key input is not registered by PSQL CLI tool.
>
> *Desktop (please complete the following information):*
>
>    - OS: MacOS Sonoma
>    - Version: 14.0
>    - Mode: Desktop
>    - Keyboard: German (not German - Standard)
>
>
   Can you please create an issue on GitHub
<https://github.com/pgadmin-org/pgadmin4/issues/new/choose>?

**Comment by nikhil-mohite** [comment]
It prints `Backspace`, and `Enter` in the PSQL terminal on the `Delete` and `Return` key press.
<img width="1441" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/69510038/7207b49e-05df-444c-9525-f12b4eb9ca39">

Please check other keys as well like UpArrow, DownArrow, etc.

**Comment by nikhil-mohite** [comment]
Resolved. 
Tested on Candidate build: https://developer.pgadmin.org/builds/2023-12-11-1/
OS: macOS (Sonoma 14.1)
Mode: Desktop

**Comment by Jeko92** [comment]
Hello,

I am using Macbook Pro (M3) with German Keyboard.
To type blackslash I need to press Shift + Options + 7.
However, backslash is not inputed in PSQL CLI Tool .

OS: MacOS Sequoia 
Version: 15.1.1
Mode: Desktop
Keyboard: German (QWERTZ)


this issue has been marked as done, but it seems that option key still doesn't apply and I can't find alternative how can I write backward slash into PSQL tool. Any tips would be much appreciated.  Thanks in advance

**Comment by nicou** [comment]
> Hello,
> 
> I am using Macbook Pro (M3) with German Keyboard. To type blackslash I need to press Shift + Options + 7. However, backslash is not inputed in PSQL CLI Tool .
> 
> OS: MacOS Sequoia Version: 15.1.1 Mode: Desktop Keyboard: German (QWERTZ)
> 
> this issue has been marked as done, but it seems that option key still doesn't apply and I can't find alternative how can I write backward slash into PSQL tool. Any tips would be much appreciated. Thanks in advance

Same here on Sonoma 14.6.1 (23G93) and Finnish keyboard layout.

**Comment by pravesh-sharma** [comment]
Reopening as the issue is reproducible.

**Comment by yogeshmahajan-1903** [comment]
Backspace and Enter keys are not working.

**Comment by yogeshmahajan-1903** [comment]
This is working fine.

**Comment by barunps3** [comment]
Why is Backspace and Enter key of importance if actually Options key is not getting registered correctly? Why is the ticket closed after only backspace and enter key being tested ?

**Comment by yogeshmahajan-1903** [comment]
@barunps3 
Both issues are fixed on latest snapshot build, hence ticket is closed. Can you please check with latest nightly build?

**Comment by Penguin975** [comment]
Can this fix please be enhanced so that the Insert, Delete, Home, End, and PageUp, PageDown keys are also not echoed to the psql terminal? Trying to edit SQL in a PgAdmin 9.0 psql window is very annoying when you hit one of these keys and the key name is displayed, which obviously will cause SQL syntax error.
