### ISSUE TITLE
pgadmin4 not working after upgrade to Ubuntu 24.04 Noble

### ISSUE THREAD

**Issue by sanjayminni** [pgadmin-org/pgadmin4#7437]
After upgrade to  Ubuntu 24.04 Noble the existing installation has stopped working and is throwing error below: 

pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/usr/pgadmin4/venv/bin/python3"
Runtime Config File: "/home/xxx/.config/pgadmin/runtime_config.json"
pgAdmin Config File: "/usr/pgadmin4/web/config.py"
Webapp Path: "/usr/pgadmin4/web/pgAdmin4.py"
pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py"
Environment: 
  - HOME: /home/xxx
  - LANG: en_GB.UTF-8
  - LC_ADDRESS: en_IN.UTF-8
  - LC_IDENTIFICATION: en_IN.UTF-8
  - LC_MEASUREMENT: en_IN.UTF-8
  - LC_MONETARY: en_IN.UTF-8
  - LC_NAME: en_IN.UTF-8
  - LC_NUMERIC: en_IN.UTF-8
  - LC_PAPER: en_IN.UTF-8
  - LC_TELEPHONE: en_IN.UTF-8
  - LC_TIME: en_IN.UTF-8
  - LOGNAME: xxx
  - PATH: xxx
  - SHELL: /bin/bash
  - USER: xxx
  - XDG_RUNTIME_DIR: /run/user/1000
  - GTK_MODULES: gail:atk-bridge
  - QT_ACCESSIBILITY: 1
  - XDG_DATA_DIRS: /usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
  - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  - DEBUGINFOD_URLS: https://debuginfod.ubuntu.com 
  - DESKTOP_SESSION: ubuntu
  - GDMSESSION: ubuntu
  - GNOME_DESKTOP_SESSION_ID: this-is-deprecated
  - GNOME_SHELL_SESSION_MODE: ubuntu
  - GSM_SKIP_SSH_AGENT_WORKAROUND: true
  - IM_CONFIG_PHASE: 1
  - LANGUAGE: en_GB:en
  - LIBVIRT_DEFAULT_URI: qemu:///system
  - PAPERSIZE: a4
  - PWD: /home/xx
  - QT_IM_MODULE: ibus
  - SESSION_MANAGER: local/xxxxxxx:@/tmp/.ICE-unix/1585,unix/xxxxxxx:/tmp/.ICE-unix/1585
  - SHLVL: 0
  - SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
  - USERNAME: xx
  - XDG_CONFIG_DIRS: /etc/xdg/xdg-ubuntu:/etc/xdg
  - XDG_CURRENT_DESKTOP: ubuntu:GNOME
  - XDG_MENU_PREFIX: gnome-
  - XDG_SESSION_CLASS: user
  - XDG_SESSION_DESKTOP: ubuntu
  - XDG_SESSION_TYPE: wayland
  - XMODIFIERS: @im=ibus
  - _: /usr/bin/gnome-session
  - MANAGERPID: 1357
  - INVOCATION_ID: 453a3ffc985a457291e377c28aec5b81
  - JOURNAL_STREAM: 8:14840
  - SYSTEMD_EXEC_PID: 1625
  - MEMORY_PRESSURE_WATCH: /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/org.gnome.Shell@wayland.service/memory.pressure
  - MEMORY_PRESSURE_WRITE: c29tZSAyMDAwMDAgMjAwMDAwMAA=
  - GJS_DEBUG_OUTPUT: stderr
  - GJS_DEBUG_TOPICS: JS ERROR;JS LOG
  - GNOME_SETUP_DISPLAY: :1
  - DISPLAY: :0
  - XAUTHORITY: /run/user/1000/.mutter-Xwaylandauth.Y5NFM2
  - WAYLAND_DISPLAY: wayland-0
  - GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/pgadmin4.desktop
  - GIO_LAUNCHED_DESKTOP_FILE_PID: 15250
  - GDK_BACKEND: x11
  - NO_AT_BRIDGE: 1
  - PGADMIN_INT_PORT: 36893
  - PGADMIN_INT_KEY: 61652ca5-4788-4855-b84c-879a28f99ebb
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.021 Sec
Failed to launch pgAdmin4. Error:
Error: spawn /usr/pgadmin4/venv/bin/python3 ENOENT

**Comment by RuizSenior** [comment]
same

**Comment by abdur8312** [comment]
For me also. I upgraded from 23.10 to 22.04 today. when i try to install pgadmin4, it was not at all installing.

**Comment by KostyanM** [comment]
I`ve get 'The repository 'https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/noble pgadmin4 Release' does not have a Release file.'

**Comment by jasonsemko** [comment]
Echoing this. I do see on the downloads that 24 is not yet listed for support. Any indication when it will be supported? Thanks

**Comment by fuattatar** [comment]
Same issue on ubuntu 24.04

pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/usr/pgadmin4/venv/bin/python3"
Runtime Config File: "/home/fuat/.config/pgadmin/runtime_config.json"
pgAdmin Config File: "/usr/pgadmin4/web/config.py"
Webapp Path: "/usr/pgadmin4/web/pgAdmin4.py"
pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py"
Environment: 
  - HOME: /home/fuat
  - LANG: tr_TR.UTF-8
  - LOGNAME: fuat
  - PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
  - SHELL: /bin/bash
  - USER: fuat
  - XDG_RUNTIME_DIR: /run/user/1000
  - GTK_MODULES: gail:atk-bridge
  - QT_ACCESSIBILITY: 1
  - XDG_DATA_DIRS: /usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
  - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  - DEBUGINFOD_URLS: https://debuginfod.ubuntu.com 
  - DESKTOP_SESSION: ubuntu
  - GDMSESSION: ubuntu
  - GNOME_DESKTOP_SESSION_ID: this-is-deprecated
  - GNOME_SHELL_SESSION_MODE: ubuntu
  - GSM_SKIP_SSH_AGENT_WORKAROUND: true
  - IM_CONFIG_PHASE: 1
  - PWD: /home/fuat
  - QT_IM_MODULE: ibus
  - SESSION_MANAGER: local/fuat-IdeaPad-1-15ALC7:@/tmp/.ICE-unix/1973,unix/fuat-IdeaPad-1-15ALC7:/tmp/.ICE-unix/1973
  - SHLVL: 0
  - SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
  - USERNAME: fuat
  - XDG_CONFIG_DIRS: /etc/xdg/xdg-ubuntu:/etc/xdg
  - XDG_CURRENT_DESKTOP: ubuntu:GNOME
  - XDG_MENU_PREFIX: gnome-
  - XDG_SESSION_CLASS: user
  - XDG_SESSION_DESKTOP: ubuntu
  - XDG_SESSION_TYPE: wayland
  - XMODIFIERS: @im=ibus
  - _: /usr/bin/gnome-session
  - MANAGERPID: 1750
  - INVOCATION_ID: b0bf3880a1d94a78a676bc4c5a998521
  - JOURNAL_STREAM: 8:16319
  - SYSTEMD_EXEC_PID: 2016
  - MEMORY_PRESSURE_WATCH: /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/org.gnome.Shell@wayland.service/memory.pressure
  - MEMORY_PRESSURE_WRITE: c29tZSAyMDAwMDAgMjAwMDAwMAA=
  - GJS_DEBUG_OUTPUT: stderr
  - GJS_DEBUG_TOPICS: JS ERROR;JS LOG
  - GNOME_SETUP_DISPLAY: :1
  - DISPLAY: :0
  - XAUTHORITY: /run/user/1000/.mutter-Xwaylandauth.SAURM2
  - WAYLAND_DISPLAY: wayland-0
  - GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/pgadmin4.desktop
  - GIO_LAUNCHED_DESKTOP_FILE_PID: 23283
  - GDK_BACKEND: x11
  - NO_AT_BRIDGE: 1
  - PGADMIN_INT_PORT: 42773
  - PGADMIN_INT_KEY: 6fc6b587-4913-4160-9630-ce71d685b18c
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.008 Sec
Failed to launch pgAdmin4. Error:
Error: spawn /usr/pgadmin4/venv/bin/python3 ENOENT

**Comment by avinasx** [comment]
any update on support to ubuntu 24.04?

**Comment by sapachecon** [comment]
Same thing, I just installed Ubuntu 24.04 and I can't find how to install pgadmin4!!...Would it have been a good idea to install Ubuntu 24.04?

**Comment by adityatoshniwal** [comment]
HI @sanjayminni,
Please share the output of `ls -l /usr/pgadmin4/venv/bin/python3`

**Comment by sanjayminni** [comment]
Hi @adityatoshniwal 
output is 
lrwxrwxrwx 1 root root 19 Apr  1 17:21 /usr/pgadmin4/venv/bin/python3 -> /usr/bin/python3.11

> HI @sanjayminni, Please share the output of `ls -l /usr/pgadmin4/venv/bin/python3`

**Comment by adityatoshniwal** [comment]
> Hi @adityatoshniwal output is lrwxrwxrwx 1 root root 19 Apr 1 17:21 /usr/pgadmin4/venv/bin/python3 -> /usr/bin/python3.11
> 
> > HI @sanjayminni, Please share the output of `ls -l /usr/pgadmin4/venv/bin/python3`

And is the `/usr/bin/python3.11` present? I'm suspecting the symlink is broken after upgrade. Please give the output for `ls -l /usr/bin/python*`

**Comment by adityatoshniwal** [comment]
Ubuntu Noble is not yet supported by pgAdmin. So this is a feature and not a bug. One can check the supported versions here - https://www.pgadmin.org/download/pgadmin-4-apt/

**Comment by sanjayminni** [comment]
> > Hi @adityatoshniwal output is lrwxrwxrwx 1 root root 19 Apr 1 17:21 /usr/pgadmin4/venv/bin/python3 -> /usr/bin/python3.11
> > > HI @sanjayminni, Please share the output of `ls -l /usr/pgadmin4/venv/bin/python3`
> 
> And is the `/usr/bin/python3.11` present? I'm suspecting the symlink is broken after upgrade. Please give the output for `ls -l /usr/bin/python*`

@adityatoshniwal 
Here is the output:
lrwxrwxrwx 1 root root      10 Apr 12 18:59 /usr/bin/python3 -> python3.12
-rwxr-xr-x 1 root root 8019136 Apr 10 11:03 /usr/bin/python3.12
(Ok seems python 3.11 has been upgraded to python 3.12)

**Comment by adityatoshniwal** [comment]
@sanjayminni,
run the following commands and then try:
```
rm -f /usr/pgadmin4/venv/bin/python3
ln -s /usr/bin/python3 /usr/pgadmin4/venv/bin/python3
```

**Comment by sanjayminni** [comment]
@adityatoshniwal 

> Ubuntu Noble is not yet supported by pgAdmin. So this is a feature and not a bug. One can check the supported versions here - https://www.pgadmin.org/download/pgadmin-4-apt/

I do wish pgAdmin would not be so tied to OS release - IIRC pgadmin broke down on the previous 2 Ubuntu releases also and the mantic fix took a while. 
Its a catch-22 situation between installing an OS release upgrade only if pgadmin supports the os and knowing if pgadmin4 works on the release - ... or other way is to wait till pgadmin lists the OS version as supported.

**Comment by sanjayminni** [comment]
> @sanjayminni, run the following commands and then try:
> 
> ```
> rm -f /usr/pgadmin4/venv/bin/python3
> ln -s /usr/bin/python3 /usr/pgadmin4/venv/bin/python3
> ```

Nope I get
**The pgAdmin 4 server could not be contacted:**

pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/usr/pgadmin4/venv/bin/python3"
Runtime Config File: "/home/sm/.config/pgadmin/runtime_config.json"
pgAdmin Config File: "/usr/pgadmin4/web/config.py"
Webapp Path: "/usr/pgadmin4/web/pgAdmin4.py"
pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py"
Environment: 
  - HOME: /home/sm
  - LANG: en_GB.UTF-8
  - LC_ADDRESS: en_IN.UTF-8
  - LC_IDENTIFICATION: en_IN.UTF-8
  - LC_MEASUREMENT: en_IN.UTF-8
  - LC_MONETARY: en_IN.UTF-8
  - LC_NAME: en_IN.UTF-8
  - LC_NUMERIC: en_IN.UTF-8
  - LC_PAPER: en_IN.UTF-8
  - LC_TELEPHONE: en_IN.UTF-8
  - LC_TIME: en_IN.UTF-8
  - LOGNAME: sm
  - PATH: /home/sm/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
  - SHELL: /bin/bash
  - USER: sm
  - XDG_RUNTIME_DIR: /run/user/1000
  - GTK_MODULES: gail:atk-bridge
  - QT_ACCESSIBILITY: 1
  - XDG_DATA_DIRS: /usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
  - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  - DEBUGINFOD_URLS: https://debuginfod.ubuntu.com 
  - DESKTOP_SESSION: ubuntu
  - GDMSESSION: ubuntu
  - GNOME_DESKTOP_SESSION_ID: this-is-deprecated
  - GNOME_SHELL_SESSION_MODE: ubuntu
  - GSM_SKIP_SSH_AGENT_WORKAROUND: true
  - IM_CONFIG_PHASE: 1
  - LANGUAGE: en_GB:en
  - LIBVIRT_DEFAULT_URI: qemu:///system
  - PAPERSIZE: a4
  - PWD: /home/sm
  - QT_IM_MODULE: ibus
  - SESSION_MANAGER: local/smDD1u:@/tmp/.ICE-unix/1668,unix/smDD1u:/tmp/.ICE-unix/1668
  - SHLVL: 0
  - SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
  - USERNAME: sm
  - XDG_CONFIG_DIRS: /etc/xdg/xdg-ubuntu:/etc/xdg
  - XDG_CURRENT_DESKTOP: ubuntu:GNOME
  - XDG_MENU_PREFIX: gnome-
  - XDG_SESSION_CLASS: user
  - XDG_SESSION_DESKTOP: ubuntu
  - XDG_SESSION_TYPE: wayland
  - XMODIFIERS: @im=ibus
  - _: /usr/bin/gnome-session
  - MANAGERPID: 1444
  - INVOCATION_ID: 776f13cc4714413d8c20274f11156d64
  - JOURNAL_STREAM: 8:14221
  - SYSTEMD_EXEC_PID: 1701
  - MEMORY_PRESSURE_WATCH: /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/org.gnome.Shell@wayland.service/memory.pressure
  - MEMORY_PRESSURE_WRITE: c29tZSAyMDAwMDAgMjAwMDAwMAA=
  - GJS_DEBUG_OUTPUT: stderr
  - GJS_DEBUG_TOPICS: JS ERROR;JS LOG
  - GNOME_SETUP_DISPLAY: :1
  - DISPLAY: :0
  - XAUTHORITY: /run/user/1000/.mutter-Xwaylandauth.D89UM2
  - WAYLAND_DISPLAY: wayland-0
  - GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/pgadmin4.desktop
  - GIO_LAUNCHED_DESKTOP_FILE_PID: 7842
  - GDK_BACKEND: x11
  - NO_AT_BRIDGE: 1
  - PGADMIN_INT_PORT: 37199
  - PGADMIN_INT_KEY: 6d336b07-ca1d-40e8-9eec-00df7165ea70
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.02 Sec
Traceback (most recent call last):
  File "/usr/pgadmin4/web/pgAdmin4.py", line 48, in <module>

    import config
  File "/usr/pgadmin4/web/config.py", line 33, in <module>
    from pgadmin.utils import env, IS_WIN, fs_short_path
  File "/usr/pgadmin4/web/pgadmin/__init__.py", line 24, in <module>
    from flask import Flask, abort, request, current_app, session, url_for
ModuleNotFoundError: No module named 'flask'

**Comment by adityatoshniwal** [comment]
> @adityatoshniwal
> 
> > Ubuntu Noble is not yet supported by pgAdmin. So this is a feature and not a bug. One can check the supported versions here - https://www.pgadmin.org/download/pgadmin-4-apt/
> 
> I do wish pgAdmin would not be so tied to OS release - IIRC pgadmin broke down on the previous 2 Ubuntu releases also and the mantic fix took a while. Its a catch-22 situation between installing an OS release upgrade only if pgadmin supports the os and knowing if pgadmin4 works on the release - ... or other way is to wait till pgadmin lists the OS version as supported.

There's a lot of effort involved in supporting one OS version as we need to make changes in build machines and also test the release builds. What we need to do better is to be aware of next major release date so we can plan things accordingly.

**Comment by sanjayminni** [comment]
I do understand and appreciate the effort and complexity involved. I am using quite a few tools which seem to work across.

anyway any idea by when this may get working or a workaround suggested
thanks

**Comment by yogeshmahajan-1903** [comment]
@sanjayminni 

WA is to install python version 3.11.

```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.11
```

After this pgAdmin will be working. 
If you have still issue then, check symlink for venv  as below
```
$ ls -l /usr/pgadmin4/venv/bin/python3
lrwxrwxrwx 1 root root 19 Apr  1 17:21 /usr/pgadmin4/venv/bin/python3 -> /usr/bin/python3.11
$
```

To correct the symlinks run
```
ln -s /usr/bin/python3.11 /usr/pgadmin4/venv/bin/python3
```

**Comment by sanjayminni** [comment]
worked thanks

note on line 
`ln -s /usr/bin/python3.11 /usr/pgadmin4/venv/bin/python3` 
i got the error message 
ln: failed to create symbolic link '/usr/pgadmin4/venv/bin/python3': File exists
so i deleted the file
`sudo rm /usr/pgadmin4/venv/bin/python3`
and then it worked

**Comment by Hanzala47** [comment]
> After upgrade to Ubuntu 24.04 Noble the existing installation has stopped working and is throwing error below:
> 
> ## pgAdmin Runtime Environment
> Python Path: "/usr/pgadmin4/venv/bin/python3" Runtime Config File: "/home/xxx/.config/pgadmin/runtime_config.json" pgAdmin Config File: "/usr/pgadmin4/web/config.py" Webapp Path: "/usr/pgadmin4/web/pgAdmin4.py" pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py" Environment:
> 
> * HOME: /home/xxx
> * LANG: en_GB.UTF-8
> * LC_ADDRESS: en_IN.UTF-8
> * LC_IDENTIFICATION: en_IN.UTF-8
> * LC_MEASUREMENT: en_IN.UTF-8
> * LC_MONETARY: en_IN.UTF-8
> * LC_NAME: en_IN.UTF-8
> * LC_NUMERIC: en_IN.UTF-8
> * LC_PAPER: en_IN.UTF-8
> * LC_TELEPHONE: en_IN.UTF-8
> * LC_TIME: en_IN.UTF-8
> * LOGNAME: xxx
> * PATH: xxx
> * SHELL: /bin/bash
> * USER: xxx
> * XDG_RUNTIME_DIR: /run/user/1000
> * GTK_MODULES: gail:atk-bridge
> * QT_ACCESSIBILITY: 1
> * XDG_DATA_DIRS: /usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
> * DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
> * DEBUGINFOD_URLS: https://debuginfod.ubuntu.com
> * DESKTOP_SESSION: ubuntu
> * GDMSESSION: ubuntu
> * GNOME_DESKTOP_SESSION_ID: this-is-deprecated
> * GNOME_SHELL_SESSION_MODE: ubuntu
> * GSM_SKIP_SSH_AGENT_WORKAROUND: true
> * IM_CONFIG_PHASE: 1
> * LANGUAGE: en_GB:en
> * LIBVIRT_DEFAULT_URI: qemu:///system
> * PAPERSIZE: a4
> * PWD: /home/xx
> * QT_IM_MODULE: ibus
> * SESSION_MANAGER: local/xxxxxxx:@/tmp/.ICE-unix/1585,unix/xxxxxxx:/tmp/.ICE-unix/1585
> * SHLVL: 0
> * SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
> * USERNAME: xx
> * XDG_CONFIG_DIRS: /etc/xdg/xdg-ubuntu:/etc/xdg
> * XDG_CURRENT_DESKTOP: ubuntu:GNOME
> * XDG_MENU_PREFIX: gnome-
> * XDG_SESSION_CLASS: user
> * XDG_SESSION_DESKTOP: ubuntu
> * XDG_SESSION_TYPE: wayland
> * XMODIFIERS: @im=ibus
> * _: /usr/bin/gnome-session
> * MANAGERPID: 1357
> * INVOCATION_ID: 453a3ffc985a457291e377c28aec5b81
> * JOURNAL_STREAM: 8:14840
> * SYSTEMD_EXEC_PID: 1625
> * MEMORY_PRESSURE_WATCH: /sys/fs/cgroup/user.slice/user-1000.slice/[user@1000.service](mailto:user@1000.service)/session.slice/[org.gnome.Shell@wayland.service](mailto:org.gnome.Shell@wayland.service)/memory.pressure
> * MEMORY_PRESSURE_WRITE: c29tZSAyMDAwMDAgMjAwMDAwMAA=
> * GJS_DEBUG_OUTPUT: stderr
> * GJS_DEBUG_TOPICS: JS ERROR;JS LOG
> * GNOME_SETUP_DISPLAY: :1
> * DISPLAY: :0
> * XAUTHORITY: /run/user/1000/.mutter-Xwaylandauth.Y5NFM2
> * WAYLAND_DISPLAY: wayland-0
> * GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/pgadmin4.desktop
> * GIO_LAUNCHED_DESKTOP_FILE_PID: 15250
> * GDK_BACKEND: x11
> * NO_AT_BRIDGE: 1
> * PGADMIN_INT_PORT: 36893
> * PGADMIN_INT_KEY: 61652ca5-4788-4855-b84c-879a28f99ebb
> * PGADMIN_SERVER_MODE: OFF
> 
> Total spawn time to start the pgAdmin4 server: 0.021 Sec Failed to launch pgAdmin4. Error: Error: spawn /usr/pgadmin4/venv/bin/python3 ENOENT



> After upgrade to Ubuntu 24.04 Noble the existing installation has stopped working and is throwing error below:
> 
> ## pgAdmin Runtime Environment
> Python Path: "/usr/pgadmin4/venv/bin/python3" Runtime Config File: "/home/xxx/.config/pgadmin/runtime_config.json" pgAdmin Config File: "/usr/pgadmin4/web/config.py" Webapp Path: "/usr/pgadmin4/web/pgAdmin4.py" pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py" Environment:
> 
> * HOME: /home/xxx
> * LANG: en_GB.UTF-8
> * LC_ADDRESS: en_IN.UTF-8
> * LC_IDENTIFICATION: en_IN.UTF-8
> * LC_MEASUREMENT: en_IN.UTF-8
> * LC_MONETARY: en_IN.UTF-8
> * LC_NAME: en_IN.UTF-8
> * LC_NUMERIC: en_IN.UTF-8
> * LC_PAPER: en_IN.UTF-8
> * LC_TELEPHONE: en_IN.UTF-8
> * LC_TIME: en_IN.UTF-8
> * LOGNAME: xxx
> * PATH: xxx
> * SHELL: /bin/bash
> * USER: xxx
> * XDG_RUNTIME_DIR: /run/user/1000
> * GTK_MODULES: gail:atk-bridge
> * QT_ACCESSIBILITY: 1
> * XDG_DATA_DIRS: /usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
> * DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
> * DEBUGINFOD_URLS: https://debuginfod.ubuntu.com
> * DESKTOP_SESSION: ubuntu
> * GDMSESSION: ubuntu
> * GNOME_DESKTOP_SESSION_ID: this-is-deprecated
> * GNOME_SHELL_SESSION_MODE: ubuntu
> * GSM_SKIP_SSH_AGENT_WORKAROUND: true
> * IM_CONFIG_PHASE: 1
> * LANGUAGE: en_GB:en
> * LIBVIRT_DEFAULT_URI: qemu:///system
> * PAPERSIZE: a4
> * PWD: /home/xx
> * QT_IM_MODULE: ibus
> * SESSION_MANAGER: local/xxxxxxx:@/tmp/.ICE-unix/1585,unix/xxxxxxx:/tmp/.ICE-unix/1585
> * SHLVL: 0
> * SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
> * USERNAME: xx
> * XDG_CONFIG_DIRS: /etc/xdg/xdg-ubuntu:/etc/xdg
> * XDG_CURRENT_DESKTOP: ubuntu:GNOME
> * XDG_MENU_PREFIX: gnome-
> * XDG_SESSION_CLASS: user
> * XDG_SESSION_DESKTOP: ubuntu
> * XDG_SESSION_TYPE: wayland
> * XMODIFIERS: @im=ibus
> * _: /usr/bin/gnome-session
> * MANAGERPID: 1357
> * INVOCATION_ID: 453a3ffc985a457291e377c28aec5b81
> * JOURNAL_STREAM: 8:14840
> * SYSTEMD_EXEC_PID: 1625
> * MEMORY_PRESSURE_WATCH: /sys/fs/cgroup/user.slice/user-1000.slice/[user@1000.service](mailto:user@1000.service)/session.slice/[org.gnome.Shell@wayland.service](mailto:org.gnome.Shell@wayland.service)/memory.pressure
> * MEMORY_PRESSURE_WRITE: c29tZSAyMDAwMDAgMjAwMDAwMAA=
> * GJS_DEBUG_OUTPUT: stderr
> * GJS_DEBUG_TOPICS: JS ERROR;JS LOG
> * GNOME_SETUP_DISPLAY: :1
> * DISPLAY: :0
> * XAUTHORITY: /run/user/1000/.mutter-Xwaylandauth.Y5NFM2
> * WAYLAND_DISPLAY: wayland-0
> * GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/pgadmin4.desktop
> * GIO_LAUNCHED_DESKTOP_FILE_PID: 15250
> * GDK_BACKEND: x11
> * NO_AT_BRIDGE: 1
> * PGADMIN_INT_PORT: 36893
> * PGADMIN_INT_KEY: 61652ca5-4788-4855-b84c-879a28f99ebb
> * PGADMIN_SERVER_MODE: OFF
> 
> Total spawn time to start the pgAdmin4 server: 0.021 Sec Failed to launch pgAdmin4. Error: Error: spawn /usr/pgadmin4/venv/bin/python3 ENOENT

Having same Issue

**Comment by grizzlysmit** [comment]
> > @adityatoshniwal
> > > Ubuntu Noble is not yet supported by pgAdmin. So this is a feature and not a bug. One can check the supported versions here - https://www.pgadmin.org/download/pgadmin-4-apt/
> > 
> > 
> > I do wish pgAdmin would not be so tied to OS release - IIRC pgadmin broke down on the previous 2 Ubuntu releases also and the mantic fix took a while. Its a catch-22 situation between installing an OS release upgrade only if pgadmin supports the os and knowing if pgadmin4 works on the release - ... or other way is to wait till pgadmin lists the OS version as supported.
> 
> There's a lot of effort involved in supporting one OS version as we need to make changes in build machines and also test the release builds (which may require changes in code as well if things doesn't work). What we need to do better is to be aware of next major release date so we can plan things accordingly.

yeah we have to be a bit patient with this they always get there there will be a new release for 24.04 soon meanwhile do what I do keep checking their sight for the release and use a machine virtual or otherwise with an earlier ubuntu to run pgAmin4

**Comment by khushboovashi** [comment]
> any idea when pgadmin4 will be released for ubuntu 24.04?
We are targeting Ubuntu 24.04 for the June release.

**Comment by Hanzala47** [comment]
> any idea when pgadmin4 will be released for ubuntu 24.04?

Update your pgadmin4 to the latest version 8.6.
Just released yesterday.

its working now.

**Comment by notnullonline** [comment]
> > any idea when pgadmin4 will be released for ubuntu 24.04?
> 
> Update your pgadmin4 to the latest version 8.6. Just released yesterday.
> 
> its working now.

Steps please... :(

**Comment by Hanzala47** [comment]
> > > any idea when pgadmin4 will be released for ubuntu 24.04?
> > 
> > 
> > Update your pgadmin4 to the latest version 8.6. Just released yesterday.
> > its working now.
> 
> Steps please... :(

sudo apt update 
sudo apt upgrade 

if not work, then purge pgadmin4 and do fresh install

**Comment by johan-nilsson-82** [comment]
> > > > any idea when pgadmin4 will be released for ubuntu 24.04?
> > > 
> > > 
> > > Update your pgadmin4 to the latest version 8.6. Just released yesterday.
> > > its working now.
> > 
> > 
> > Steps please... :(
> 
> sudo apt update sudo apt upgrade
> 
> if not work, then purge pgadmin4 and do fresh install

I tried to install on a fresh installed Ubuntu 24.04 but still same issue for me. 

I followed the steps here: https://www.pgadmin.org/download/pgadmin-4-apt/

I had to use version **mantic** instead of **nobel** since it was not released yet. What version where you using?

This version I used: https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/mantic/

I will also make an attempt to install from source. But since you wrote that you just updated and upgraded I assume that you use the packet manager also.

**Comment by JoaoPauloK** [comment]
I just installed python3.11 aside native python.12 and pointed the symbolic link to python3.11 instead. It worked.

**Comment by Mikhail42** [comment]
for me the solution it to use another Postgres DB client, like DBeaver...

**Comment by yorickdowne** [comment]
Works without issue and without going for 3.11 here, on `mantic` apt package and pgadmin4 `8.6`.

**Comment by KostyanM** [comment]
Guys, it works okay if install pgadmin into virtual environment. At download page pgadmin site see python version installing

**Comment by gp-abhishek** [comment]
> @sanjayminni
> 
> WA is to install python version 3.11.
> 
> ```
> sudo add-apt-repository ppa:deadsnakes/ppa
> sudo apt update
> sudo apt install python3.11
> ```
> 
> After this pgAdmin will be working. If you have still issue then, check symlink for venv as below
> 
> ```
> $ ls -l /usr/pgadmin4/venv/bin/python3
> lrwxrwxrwx 1 root root 19 Apr  1 17:21 /usr/pgadmin4/venv/bin/python3 -> /usr/bin/python3.11
> $
> ```
> 
> To correct the symlinks run
> 
> ```
> ln -s /usr/bin/python3.11 /usr/pgadmin4/venv/bin/python3
> ```

Thanks a lot, installing python 3.11 worked for me

but i had to do 

```
sudo apt remove libpython3.11-minimal libpython3.11-stdlib python3.11-minimal python3.11
```

**Comment by AnkahHarrison** [comment]
![Screenshot from 2024-05-14 20-32-36](https://github.com/pgadmin-org/pgadmin4/assets/103390535/c62d9341-d008-4caa-8482-954f155fbccd)
i did all this as required but still pgadmin4 is not working
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.11


$ ls -l /usr/pgadmin4/venv/bin/python3

**Comment by AnkahHarrison** [comment]
pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/usr/pgadmin4/venv/bin/python3"
Runtime Config File: "/home/seyram/.config/pgadmin/runtime_config.json"
pgAdmin Config File: "/usr/pgadmin4/web/config.py"
Webapp Path: "/usr/pgadmin4/web/pgAdmin4.py"
pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py"
Environment: 
  - HOME: /home/seyram
  - LANG: en_US.UTF-8
  - LOGNAME: seyram
  - PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
  - SHELL: /bin/bash
  - USER: seyram
  - XDG_RUNTIME_DIR: /run/user/1000
  - GTK_MODULES: gail:atk-bridge
  - QT_ACCESSIBILITY: 1
  - XDG_DATA_DIRS: /usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
  - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  - DEBUGINFOD_URLS: https://debuginfod.ubuntu.com 
  - DESKTOP_SESSION: ubuntu
  - GDMSESSION: ubuntu
  - GNOME_DESKTOP_SESSION_ID: this-is-deprecated
  - GNOME_SHELL_SESSION_MODE: ubuntu
  - GSM_SKIP_SSH_AGENT_WORKAROUND: true
  - IM_CONFIG_PHASE: 1
  - PWD: /home/seyram
  - QT_IM_MODULE: ibus
  - SESSION_MANAGER: local/seyram:@/tmp/.ICE-unix/2783,unix/seyram:/tmp/.ICE-unix/2783
  - SHLVL: 0
  - SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
  - USERNAME: seyram
  - XDG_CONFIG_DIRS: /etc/xdg/xdg-ubuntu:/etc/xdg
  - XDG_CURRENT_DESKTOP: ubuntu:GNOME
  - XDG_MENU_PREFIX: gnome-
  - XDG_SESSION_CLASS: user
  - XDG_SESSION_DESKTOP: ubuntu
  - XDG_SESSION_TYPE: wayland
  - XMODIFIERS: @im=ibus
  - _: /usr/bin/gnome-session
  - MANAGERPID: 2532
  - INVOCATION_ID: 1ead4e26346a4d34bdfeb58668e75553
  - JOURNAL_STREAM: 8:20998
  - SYSTEMD_EXEC_PID: 2829
  - MEMORY_PRESSURE_WATCH: /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/org.gnome.Shell@wayland.service/memory.pressure
  - MEMORY_PRESSURE_WRITE: c29tZSAyMDAwMDAgMjAwMDAwMAA=
  - GJS_DEBUG_OUTPUT: stderr
  - GJS_DEBUG_TOPICS: JS ERROR;JS LOG
  - GNOME_SETUP_DISPLAY: :1
  - DISPLAY: :0
  - XAUTHORITY: /run/user/1000/.mutter-Xwaylandauth.BIGPN2
  - WAYLAND_DISPLAY: wayland-0
  - GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/pgadmin4.desktop
  - GIO_LAUNCHED_DESKTOP_FILE_PID: 3629
  - GDK_BACKEND: x11
  - NO_AT_BRIDGE: 1
  - PGADMIN_INT_PORT: 46207
  - PGADMIN_INT_KEY: 55107c68-daaf-41f7-9993-0597013e4922
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.008 Sec
Traceback (most recent call last):
  File "/usr/pgadmin4/web/pgAdmin4.py", line 48, in <module>

    import config

  File "/usr/pgadmin4/web/config.py", line 33, in <module>

    from pgadmin.utils import env, IS_WIN, fs_short_path
  File "/usr/pgadmin4/web/pgadmin/__init__.py", line 24, in <module>
    from flask import Flask, abort, request, current_app, session, url_for
ModuleNotFoundError: No module named 'flask'

![Screenshot from 2024-05-14 22-29-35](https://github.com/pgadmin-org/pgadmin4/assets/103390535/6f086be4-08f0-4682-b94b-89e02f634f9e)

**Comment by AnkahHarrison** [comment]
pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/usr/pgadmin4/venv/bin/python3"
Runtime Config File: "/home/seyram/.config/pgadmin/runtime_config.json"
pgAdmin Config File: "/usr/pgadmin4/web/config.py"
Webapp Path: "/usr/pgadmin4/web/pgAdmin4.py"
pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py"
Environment: 
  - HOME: /home/seyram
  - LANG: en_US.UTF-8
  - LOGNAME: seyram
  - PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
  - SHELL: /bin/bash
  - USER: seyram
  - XDG_RUNTIME_DIR: /run/user/1000
  - GTK_MODULES: gail:atk-bridge
  - QT_ACCESSIBILITY: 1
  - XDG_DATA_DIRS: /usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
  - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  - DEBUGINFOD_URLS: https://debuginfod.ubuntu.com 
  - DESKTOP_SESSION: ubuntu
  - GDMSESSION: ubuntu
  - GNOME_DESKTOP_SESSION_ID: this-is-deprecated
  - GNOME_SHELL_SESSION_MODE: ubuntu
  - GSM_SKIP_SSH_AGENT_WORKAROUND: true
  - IM_CONFIG_PHASE: 1
  - PWD: /home/seyram
  - QT_IM_MODULE: ibus
  - SESSION_MANAGER: local/seyram:@/tmp/.ICE-unix/2783,unix/seyram:/tmp/.ICE-unix/2783
  - SHLVL: 0
  - SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
  - USERNAME: seyram
  - XDG_CONFIG_DIRS: /etc/xdg/xdg-ubuntu:/etc/xdg
  - XDG_CURRENT_DESKTOP: ubuntu:GNOME
  - XDG_MENU_PREFIX: gnome-
  - XDG_SESSION_CLASS: user
  - XDG_SESSION_DESKTOP: ubuntu
  - XDG_SESSION_TYPE: wayland
  - XMODIFIERS: @im=ibus
  - _: /usr/bin/gnome-session
  - MANAGERPID: 2532
  - INVOCATION_ID: 1ead4e26346a4d34bdfeb58668e75553
  - JOURNAL_STREAM: 8:20998
  - SYSTEMD_EXEC_PID: 2829
  - MEMORY_PRESSURE_WATCH: /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/org.gnome.Shell@wayland.service/memory.pressure
  - MEMORY_PRESSURE_WRITE: c29tZSAyMDAwMDAgMjAwMDAwMAA=
  - GJS_DEBUG_OUTPUT: stderr
  - GJS_DEBUG_TOPICS: JS ERROR;JS LOG
  - GNOME_SETUP_DISPLAY: :1
  - DISPLAY: :0
  - XAUTHORITY: /run/user/1000/.mutter-Xwaylandauth.BIGPN2
  - WAYLAND_DISPLAY: wayland-0
  - GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/pgadmin4.desktop
  - GIO_LAUNCHED_DESKTOP_FILE_PID: 3629
  - GDK_BACKEND: x11
  - NO_AT_BRIDGE: 1
  - PGADMIN_INT_PORT: 46207
  - PGADMIN_INT_KEY: 55107c68-daaf-41f7-9993-0597013e4922
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.008 Sec
Traceback (most recent call last):
  File "/usr/pgadmin4/web/pgAdmin4.py", line 48, in <module>

    import config

  File "/usr/pgadmin4/web/config.py", line 33, in <module>

    from pgadmin.utils import env, IS_WIN, fs_short_path
  File "/usr/pgadmin4/web/pgadmin/__init__.py", line 24, in <module>
    from flask import Flask, abort, request, current_app, session, url_for
ModuleNotFoundError: No module named 'flask'

**Comment by fitiavanaeni** [comment]
![image](https://github.com/pgadmin-org/pgadmin4/assets/45180512/3827a9eb-e396-4361-afaa-b41d2f2dd6fa)


I can't resolve it
Help!

**Comment by TaeZStkyoht** [comment]
It seems it's not supported yet: https://stackoverflow.com/questions/78484580/pgadmin-package-pgadmin4-has-no-installation-candidateubuntu-24-04

**Comment by daveysyr** [comment]
On the pgadmin website, it clearly states that Ubuntu 24.04 noble is supported from V8.7 (pgadmin is currently at 8.6).  So despite the repository seeming to exist, there is nothing much inside it.

My experience so far is that the Docker version doesn't work correctly for users and neither does the Python version - both these versions assume that you have a fair bit of experience with either Docker or Python respectively.

So, if you're currently successfully using pgadmin4-desktop within a version of Ubuntu before the current 'noble' release, hold off your upgrade to the latest Ubuntu version until the next pgadmin version (8.7) is released sometime in June 2024.

**Comment by akshay-joshi** [comment]
Hi All

It will be available from v8.7. Meanwhile, you can test on the [snapshot build.](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-05-20/)

**Comment by daveysyr** [comment]
Hi, and thanks for commenting.

I tried what you suggested and the desktop app is working for me now on Ubuntu Noble, so thank you very much for that!!

Being able to run pgadmin as a desktop app is super-useful for me.  I'll certainly be more careful around checking compatibility next time I upgrade Ubuntu!

Regards,
Dave.



> Hi All
> 
> 
> 
> It will be available from v8.7. Meanwhile, you can test on the [snapshot build.](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-05-20/)
> 
> It would help us to know any issues in advance.

**Comment by fuattatar** [comment]
> Hi All
> 
> It will be available from v8.7. Meanwhile, you can test on the [snapshot build.](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-05-20/) It would help us to know any issues in advance.

It worked thank you

**Comment by jasonsemko** [comment]
Looks like the website was updated to support Ubuntu 24, I see the fix commit as well, thank you @khushboovashi [Commit](https://github.com/pgadmin-org/pgadmin4/commit/e9f37479691187f4fa1c77ef23a964985e8b56e2 )

From my desktop I can only get 8.5 as the latest so will be waiting for 8.7

> pgadmin4-desktop is already the newest version (8.5).

**Comment by adityatoshniwal** [comment]
Tested with candidate build here https://developer.pgadmin.org/builds/2024-05-28-1
Works fine.

**Comment by ben-ba** [comment]
> Tested with candidate build here https://developer.pgadmin.org/builds/2024-05-28-1 Works fine.

so atm we need to use the following apt repo / command for installing pgadmin;

`sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://developer.pgadmin.org/builds/2024-05-28-1/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'`

**Comment by adityatoshniwal** [comment]
> so atm we need to use the following apt repo / command for installing pgadmin;
> 
> `sudo sh -c 'echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://developer.pgadmin.org/builds/2024-05-28-1/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list && apt update'`

Or you can wait till tomorrow. v8.7 is planned to be released tomorrow.

**Comment by badr69** [comment]
> @sanjayminni
> 
> WA is to install python version 3.11.
> 
> ```
> sudo add-apt-repository ppa:deadsnakes/ppa
> sudo apt update
> sudo apt install python3.11
> ```
> 
> After this pgAdmin will be working. If you have still issue then, check symlink for venv as below
> 
> ```
> $ ls -l /usr/pgadmin4/venv/bin/python3
> lrwxrwxrwx 1 root root 19 Apr  1 17:21 /usr/pgadmin4/venv/bin/python3 -> /usr/bin/python3.11
> $
> ```
> 
> To correct the symlinks run
> 
> ```
> ln -s /usr/bin/python3.11 /usr/pgadmin4/venv/bin/python3
> ```

Thanks a lot, it works with python3.11

**Comment by brunoenten** [comment]
I've built a snap of pgadmin4 8.6 that works with Ubuntu 24.04 noble:

[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/pgadmin4)

Hopefully it will help keep pgadmin4 working even after future Ubuntu release upgrades.

**Comment by fuattatar** [comment]
> I've built a snap of pgadmin4 8.6 that works with Ubuntu 24.04 noble:
> 
> [![Get it from the Snap Store](https://camo.githubusercontent.com/46aa03c94aa80f6545e01f2ce3966a1d7ae73552495f177b9b71f411408ce325/68747470733a2f2f736e617063726166742e696f2f7374617469632f696d616765732f6261646765732f656e2f736e61702d73746f72652d626c61636b2e737667)](https://snapcraft.io/pgadmin4)
> 
> Hopefully it will help keep pgadmin4 working even after future Ubuntu release upgrades.

Snap version does not work.

![image](https://github.com/pgadmin-org/pgadmin4/assets/2419809/a2858ddd-b90f-49b1-950e-ea496d01b329)

pgAdmin Runtime Environment
--------------------------------------------------------
Python Path: "/snap/pgadmin4/2/usr/pgadmin4/venv/bin/python3"
Runtime Config File: "/home/fuat/snap/pgadmin4/2/.config/pgadmin/runtime_config.json"
pgAdmin Config File: "/snap/pgadmin4/2/usr/pgadmin4/web/config.py"
Webapp Path: "/snap/pgadmin4/2/usr/pgadmin4/web/pgAdmin4.py"
pgAdmin Command: "/snap/pgadmin4/2/usr/pgadmin4/venv/bin/python3 -s /snap/pgadmin4/2/usr/pgadmin4/web/pgAdmin4.py"
Environment: 
  - SHELL: /bin/bash
  - SESSION_MANAGER: local/fuat-IdeaPad-1-15ALC7:@/tmp/.ICE-unix/2466,unix/fuat-IdeaPad-1-15ALC7:/tmp/.ICE-unix/2466
  - QT_ACCESSIBILITY: 1
  - __EGL_VENDOR_LIBRARY_DIRS: /snap/pgadmin4/2/gnome-platform/usr/share/glvnd/egl_vendor.d
  - SNAP_REVISION: 2
  - XDG_CONFIG_DIRS: /snap/pgadmin4/2/gnome-platform/etc/xdg:/etc/xdg/xdg-ubuntu:/etc/xdg
  - XDG_MENU_PREFIX: gnome-
  - GNOME_DESKTOP_SESSION_ID: this-is-deprecated
  - CLUTTER_BACKEND: wayland
  - SNAP_REAL_HOME: /home/fuat
  - SNAP_USER_COMMON: /home/fuat/snap/pgadmin4/common
  - FONTCONFIG_PATH: /snap/pgadmin4/2/gnome-platform/etc/fonts
  - LANGUAGE: en
  - LC_ADDRESS: tr_TR.UTF-8
  - GNOME_SHELL_SESSION_MODE: ubuntu
  - LC_NAME: tr_TR.UTF-8
  - SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
  - XDG_DATA_HOME: /home/fuat/snap/pgadmin4/2/.local/share
  - GNOTIFICATION_BACKEND: freedesktop
  - PIPEWIRE_MODULE_DIR: /snap/pgadmin4/2/gnome-platform/usr/lib/x86_64-linux-gnu/pipewire-0.3
  - XDG_CONFIG_HOME: /home/fuat/snap/pgadmin4/2/.config
  - XCURSOR_PATH: /snap/pgadmin4/2/data-dir/icons:/snap/pgadmin4/2/gnome-platform/usr/share/icons
  - MEMORY_PRESSURE_WRITE: c29tZSAyMDAwMDAgMjAwMDAwMAA=
  - SNAP_INSTANCE_KEY: 
  - XMODIFIERS: @im=ibus
  - DESKTOP_SESSION: ubuntu
  - LC_MONETARY: tr_TR.UTF-8
  - GDK_PIXBUF_MODULE_FILE: /home/fuat/snap/pgadmin4/common/.cache/gdk-pixbuf-loaders.cache
  - BAMF_DESKTOP_FILE_HINT: /var/lib/snapd/desktop/applications/pgadmin4_pgadmin4.desktop
  - GTK_MODULES: gail:atk-bridge
  - SNAP_EUID: 1000
  - PWD: /home/fuat
  - XDG_SESSION_DESKTOP: ubuntu
  - LOGNAME: fuat
  - XDG_SESSION_TYPE: wayland
  - SYSTEMD_EXEC_PID: 9835
  - SPA_PLUGIN_DIR: /snap/pgadmin4/2/gnome-platform/usr/lib/x86_64-linux-gnu/spa-0.2
  - XAUTHORITY: /run/user/1000/.mutter-Xwaylandauth.8J0HO2
  - TEMPDIR: /tmp
  - SNAP_CONTEXT: 9sdVqUDzKLn1NPIkGN647aYDvcrjYW5Tg5MNOp9D9lD1MLWk9p3v
  - GST_PLUGIN_SCANNER: /snap/pgadmin4/2/gnome-platform/usr/lib/x86_64-linux-gnu/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner
  - LD_PRELOAD: :/snap/pgadmin4/2/gnome-platform/$LIB/bindtextdomain.so
  - GI_TYPELIB_PATH: /snap/pgadmin4/2/gnome-platform/usr/lib/girepository-1.0:/snap/pgadmin4/2/gnome-platform/usr/lib/x86_64-linux-gnu/girepository-1.0
  - HOME: /home/fuat/snap/pgadmin4/2
  - USERNAME: fuat
  - IM_CONFIG_PHASE: 1
  - LC_PAPER: tr_TR.UTF-8
  - LANG: en_US.UTF-8
  - XDG_CURRENT_DESKTOP: ubuntu:GNOME
  - MEMORY_PRESSURE_WATCH: /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/run-r7fa14cef2ea8464489537f4e42fae495.service/memory.pressure
  - WAYLAND_DISPLAY: wayland-0
  - SNAP_ARCH: amd64
  - SNAP_INSTANCE_NAME: pgadmin4
  - SNAP_USER_DATA: /home/fuat/snap/pgadmin4/2
  - TMPDIR: /tmp
  - INVOCATION_ID: 59ae235a193b43c38b403851f505bde2
  - SNAP_DESKTOP_RUNTIME: /snap/pgadmin4/2/gnome-platform
  - SNAP_LAUNCHER_ARCH_TRIPLET: x86_64-linux-gnu
  - MANAGERPID: 2184
  - SNAP_REEXEC: 
  - SNAP_UID: 1000
  - PIPEWIRE_CONFIG_DIR: /snap/pgadmin4/2/gnome-platform/usr/share/pipewire
  - QT_QPA_PLATFORM: wayland-egl
  - XDG_CACHE_HOME: /home/fuat/snap/pgadmin4/common/.cache
  - GNOME_SETUP_DISPLAY: :1
  - XDG_SESSION_CLASS: user
  - LIBGWEATHER_LOCATIONS_PATH: /snap/pgadmin4/2/gnome-platform/usr/lib/x86_64-linux-gnu/libgweather-4/Locations.bin
  - PYTHONPATH: /snap/pgadmin4/2/gnome-platform/usr/lib/python3/dist-packages
  - LC_IDENTIFICATION: tr_TR.UTF-8
  - GTK_PATH: /snap/pgadmin4/2/gnome-platform/usr/lib/x86_64-linux-gnu/gtk-2.0:/snap/pgadmin4/2/gnome-platform/usr/lib/gtk-2.0:/snap/pgadmin4/2/gnome-platform/usr/lib/x86_64-linux-gnu/gtk-3.0:/snap/pgadmin4/2/gnome-platform/usr/lib/gtk-3.0:/snap/pgadmin4/2/gnome-platform/usr/lib/x86_64-linux-gnu/gtk-4.0
  - XLOCALEDIR: /snap/pgadmin4/2/gnome-platform/usr/share/X11/locale
  - LIBTHAI_DICTDIR: /snap/pgadmin4/2/gnome-platform/usr/share/libthai/
  - USER: fuat
  - SNAP: /snap/pgadmin4/2
  - SNAP_COMMON: /var/snap/pgadmin4/common
  - SNAP_VERSION: 8.6
  - DISPLAY: :0
  - SHLVL: 0
  - GDK_PIXBUF_MODULEDIR: /snap/pgadmin4/2/gnome-platform/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders
  - LOCPATH: /snap/pgadmin4/2/gnome-platform/usr/lib/locale
  - SNAP_LIBRARY_PATH: /var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void
  - GSM_SKIP_SSH_AGENT_WORKAROUND: true
  - SNAP_COOKIE: 9sdVqUDzKLn1NPIkGN647aYDvcrjYW5Tg5MNOp9D9lD1MLWk9p3v
  - LC_TELEPHONE: tr_TR.UTF-8
  - QT_IM_MODULE: ibus
  - LC_MEASUREMENT: tr_TR.UTF-8
  - LIBGL_DRIVERS_PATH: /snap/pgadmin4/2/gnome-platform/usr/lib/x86_64-linux-gnu/dri
  - PAPERSIZE: a4
  - SNAP_DATA: /var/snap/pgadmin4/2
  - GST_PLUGIN_PATH: /snap/pgadmin4/2/usr/lib/x86_64-linux-gnu/gstreamer-1.0
  - LD_LIBRARY_PATH: /var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void:/snap/pgadmin4/2/usr/lib:/snap/pgadmin4/2/usr/lib/x86_64-linux-gnu:/snap/pgadmin4/2/gnome-platform/lib/x86_64-linux-gnu:/snap/pgadmin4/2/gnome-platform/usr/lib/x86_64-linux-gnu:/snap/pgadmin4/2/gnome-platform/usr/lib:/snap/pgadmin4/2/gnome-platform/lib:/snap/pgadmin4/2/gnome-platform/usr/lib/x86_64-linux-gnu/dri:/var/lib/snapd/lib/gl:/snap/pgadmin4/2/gnome-platform/usr/lib/x86_64-linux-gnu/libunity:/snap/pgadmin4/2/gnome-platform/usr/lib/x86_64-linux-gnu/pulseaudio
  - XDG_RUNTIME_DIR: /run/user/1000/snap.pgadmin4
  - DEBUGINFOD_URLS: https://debuginfod.ubuntu.com 
  - LIBVA_DRIVERS_PATH: /snap/pgadmin4/2/gnome-platform/usr/lib/x86_64-linux-gnu/dri
  - LC_TIME: tr_TR.UTF-8
  - GST_PLUGIN_SYSTEM_PATH: /snap/pgadmin4/2/gnome-platform/usr/lib/x86_64-linux-gnu/gstreamer-1.0
  - FONTCONFIG_FILE: /snap/pgadmin4/2/gnome-platform/etc/fonts/fonts.conf
  - SNAP_NAME: pgadmin4
  - JOURNAL_STREAM: 8:58055
  - XDG_DATA_DIRS: /home/fuat/snap/pgadmin4/2/.local/share:/home/fuat/snap/pgadmin4/2:/snap/pgadmin4/2/data-dir:/snap/pgadmin4/2/usr/share:/snap/pgadmin4/2/gnome-platform/usr/share:/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
  - GDK_BACKEND: x11
  - PATH: /snap/pgadmin4/2/usr/sbin:/snap/pgadmin4/2/usr/bin:/snap/pgadmin4/2/sbin:/snap/pgadmin4/2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/pgadmin4/2/gnome-platform/usr/bin
  - GTK_USE_PORTAL: 1
  - GDMSESSION: ubuntu
  - GTK_IM_MODULE_FILE: /home/fuat/snap/pgadmin4/common/.cache/immodules/immodules.cache
  - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
  - VDPAU_DRIVER_PATH: /usr/lib/x86_64-linux-gnu/vdpau/
  - GIO_MODULE_DIR: /home/fuat/snap/pgadmin4/common/.cache/gio-modules
  - PULSE_SERVER: unix:/run/user/1000/snap.pgadmin4/../pulse/native
  - XKB_CONFIG_ROOT: /snap/pgadmin4/2/gnome-platform/usr/share/X11/xkb
  - LC_NUMERIC: tr_TR.UTF-8
  - NO_AT_BRIDGE: 1
  - PGADMIN_INT_PORT: 32987
  - PGADMIN_INT_KEY: afb007e4-9021-478c-9291-904345745737
  - PGADMIN_SERVER_MODE: OFF
--------------------------------------------------------

Total spawn time to start the pgAdmin4 server: 0.008 Sec
Failed to launch pgAdmin4. Error:
Error: spawn /snap/pgadmin4/2/usr/pgadmin4/venv/bin/python3 EACCES

**Comment by ben-ba** [comment]
@fuattatar 
no dirty hacks needed, version 8.7 got released yesterday morning;
https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/noble/dists/pgadmin4/main/binary-amd64/

**Comment by brunoenten** [comment]
I released a new revision of the snap with pgadmin4 8.7.

Tested working on ubuntu Noble.

Please report any issue there: https://github.com/brunoenten/pgadmin4-snap/issues

**Comment by badr69** [comment]
Thanks, but it works for me with Ubuntu 24.04.

Yahoo Mail : Recherchez, organisez, maîtrisez 
 
  Le dim., juin 2, 2024 à 11:33, Bruno ***@***.***> a écrit:   


I released a new revision of the snap with pgadmin4 8.7.

Tested working on ubuntu Noble.

Please report any issue there: https://github.com/brunoenten/pgadmin4-snap/issues

**Comment by hharng** [comment]
> @sanjayminni
> 
> WA is to install python version 3.11.
> 
> ```
> sudo add-apt-repository ppa:deadsnakes/ppa
> sudo apt update
> sudo apt install python3.11
> ```
> 
> After this pgAdmin will be working.

It worked for me. Thank you!

**Comment by daveysyr** [comment]
Once pgAdmin 8.7 was released, I just went through the standard install again and it now works fine on Ubuntu Noble as far as I can tell.

Many thanks to the users who gave the workaround of using the test build and then gave a heads-up that 8.7 was going to be released.

Thanks, Dave.

**Comment by ben-ba** [comment]
> @fuattatar 
> no dirty hacks needed, version 8.7 got released yesterday morning;
> https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/noble/dists/pgadmin4/main/binary-amd64/

9d ago.....

**Comment by Sotatek-NguyenPhu** [comment]
i've upgraded to ubuntu 24.04 today and i still have the same trouble :(

**Comment by diego-ramos** [comment]
Hi all, I just upgrade my virtual machine from 22 Jammy to 24 Noble and I had the same issue, I found the problem was with chrome-sandbox, try these on a console:

cd /usr/pgadmin4/bin    #( or what ever do you have your pgadmin4 installed )
sudo chown root:root chrome-sandbox
sudo chmod 4755 chrome-sandbox

This works for me and I get pgadmin4 back again

**Comment by JGSCORCHOS** [comment]
great advice pal!

**Comment by sardorjumamuratov** [comment]
@Leeo97one Thanks bro. You saved the day!

**Comment by luciagabi** [comment]
@Leeo97one  thank you very much! :)

**Comment by prusswan** [comment]
Just installed this on Ubuntu 24.04, following the steps at https://www.pgadmin.org/download/pgadmin-4-apt/

First time, pgadmin4 hanged and crashed (led me to this issue).
But second time, pgadmin4 worked (no changes). Pretty strange I guess

**Comment by rupal-nohwar** [comment]
@prusswan Thanks bro worked for me
